apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T06:47:57Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "9078"
  uid: 321182e4-fd2d-4421-81ca-cbadfc3f4570
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.28.116
  clusterIPs:
  - 10.104.28.116
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32764
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
